# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-04 16:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=b'', verbose_name='')),
                ('introduccion', models.CharField(max_length=25, verbose_name='introduccion')),
                ('descripcion', models.CharField(max_length=50, verbose_name='descripcion')),
                ('puntaje', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
