# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-04 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='foto',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='introduccion',
            field=models.CharField(max_length=50, verbose_name='introduccion'),
        ),
    ]
